### ISSUE TITLE
Is it possible to use morula in a polyglot monorepo?

### ISSUE THREAD

**Issue by arekkas** [Originate/morula#34]

**Comment by kevgo** [comment]
Yes, absolutely! All that Morula does is run a given shell command in each subdirectory. The best way to make that work - whether different subdirectories use different languages or not - is to create a standardized set of shell commands in each directory, and then call those via Morula. An example is https://github.com/Originate/exocom/tree/kg-circle:

- each directory contains a script `bin/setup` to prepare the code base. This script runs `npm install` for node and `go get` for Go (or whatever you use to install third-party dependencies there).
- each directory also contains a script `bin/spec`, which runs the tests
- each directory could also contain a script `bin/release` to release a new version

So, to test all my subdirectories, all I have to do is run `morula all bin/spec`. Or `morula changed bin/spec` if I only want to test the projects that my current feature branch has modified.

**Comment by arekkas** [comment]
Ahh, now I get it. I though it was supposed to be something like `morula all npm test`. I'll give it a try, thanks for the explanation!

**Comment by kevgo** [comment]
Yeah, if all your repos are guaranteed to be Node, you could do that. I prefer having those generic scripts anyways, so that I don't have to remember how exactly to setup/test/lint/deploy/build/update/publish in my various projects in various stacks. See https://github.com/originate/o-tools-node.
