### ISSUE TITLE
Skip dot directories like `.git` or `.idea`

### ISSUE THREAD

**Issue by arekkas** [Originate/morula#35]

**Comment by kevgo** [comment]
Good idea. Would you ignore all directories starting with `.`? 

Right now Morula [ignores `.git` already](https://github.com/Originate/morula/blob/master/cmd/root.go#L174), but I could see that making sense for all those hidden directories.

**Comment by arekkas** [comment]
I see, I only got the error for the `.dea` directory. I guess it makes sense to ignore those as noone that I know of creates sources in dot directories.

**Comment by kevgo** [comment]
Sounds good. This will be an easy addition. For the time being, you can add `.idea` to the `never` section of the config file to avoid running it.
