### ISSUE TITLE
Allow morula.yml to take arrays

### ISSUE THREAD

**Issue by alexdavid** [Originate/morula#41]
Right now `never` etc.. in `morula.yml` can only take a single value. There may be multiple directories in the root of the repo that are not actually sub-projects. One such example is `vendor` when working with projects with multiple go repos, `documentation`, or even subprojects that have not yet been set up to work with morula – it is easier to integrate morula if a PR could be created for one subproject at a time

**Comment by kevgo** [comment]
Yeah, I was waiting for an actual need for this. Coming very soon, like tomorrow! :)
