### ISSUE TITLE
Morula does not ignore multiple subdirectories

### ISSUE THREAD

**Issue by hugobho** [Originate/morula#47]
When executing `morula all --never=dir1 --never-dir2 build`, morula only ignores the last directory (in this case `dir2`).

When listing directories to ignore in `morula.yml`, morula doesn't ignore any of the directories listed:
```
never:
  - node_modules
  - documentation
  - bin
```

**Comment by kevgo** [comment]
fixed in [version 0.1.1](https://github.com/Originate/morula/releases/tag/0.1.1)
