### ISSUE TITLE
how to pass an array to never

### ISSUE THREAD

**Issue by arekkas** [Originate/morula#49]
```
$ cat morula.yml
before-all: ""
after-all: ""
always: ""
never:
  - ".idea"
color: true
 
$ morula all test
running test in subproject .idea ...

subproject .idea has issues
```

```
$ cat morula.yml
before-all: ""
after-all: ""
always: ""
never: ".idea"
color: true
 
$ morula all test
running test in subproject apps ...

subproject apps has issues
```

**Comment by kevgo** [comment]
Strange. We have tests for both of your use cases: https://github.com/Originate/morula/blob/master/features/never.feature

Do you have the latest version (0.1.1) installed?

**Comment by arekkas** [comment]
I did a go get but that doesn't update the code base if it exists. I'll check again later, thanks for the swift reply

**Comment by kevgo** [comment]
`morula version` tells you the version in case its unclear  :)

**Comment by arekkas** [comment]
version shows `"Morula v0.1"`, even after `go get -u`, but the issue is resolved :)
